### PR TITLE
Fix pointer events

### PR DESCRIPTION
**Pull request by dzfrias**
Make all overlay content have `pointer-events: none` so user can select/click elements as they would expect. Also fix the main landing link.

### CODE REVIEW

**Comment by ADKaster** [comment]
conflicts with navigation.astro

**Comment by versecafe** [comment]
> Make all overlay content have `pointer-events: none` so user can select/click elements as they would expect. Also fix the main landing link.

Main landing link is patched

**Comment by dzfrias** [comment]
Resolved! Thank you!

**Comment by versecafe** [comment]
Thanks that has been a really annoying issue

**Review by versecafe — APPROVED** [review]

**Pull request merged**
