### PR TITLE
refac: hero css classes to Tailwind

### PR DESCRIPTION
**Pull request by Cauatn**
note: i kept .hero and .hero_single because their appear in other places that i don't know if will break

### CODE REVIEW

**Comment by versecafe** [comment]
@Cauatn Can you share some screenshots of the differences this creates

**Review by versecafe — APPROVED** [review]

**Comment by versecafe** [comment]
@Cauatn You have merge conflicts, also you may want to squash this down to one commit

**Comment by Cauatn** [comment]
> @Cauatn You have merge conflicts, also you may want to squash this down to one commit

Sure !

**Review by ADKaster — APPROVED** [review]
@Cauatn could you please use branches for your next set of PRs instead of opening them from your master branch? I'm trying to keep this repo with the same rebase-centric worfklow as the rest of our projects. With you constantly creating merge commits on your master branch it means that the 1-2 atomic commits from your PRs are not able to be cleanly cherry-picked directly onto the master branch of the repo though the "rebase" button at the bottom of the PR.

For your hamburger menu commits that seem to have been pending at the end of this PR, you should simply create a new branch based on upstream/master, and cherry-pick those hashes onto it. Then create a PR by pushing that branch to your fork.

**Comment by Cauatn** [comment]
Yea, i'm really new in contribuing in big projects like this, definitely gonna do this !
It's always nice to see people like you take time to make responses like this, really appreciate it.

**Pull request merged**
