### PR TITLE
Convert header (navigation.astro) to Tailwind

### PR DESCRIPTION
**Pull request by TibixDev**
This small PR just converts the existing BEM CSS header to use Tailwind classes instead

### CODE REVIEW

**Comment by TibixDev** [comment]
Also, a small showcase for the differences between the units from before and my best effort to respect Tailwind ones, there's some small differences but it should be fine.

https://github.com/LadybirdBrowser/ladybird.org/assets/21055141/fd9d8304-8a18-4a72-b312-916b52bcaa54

**Review by versecafe — CHANGES_REQUESTED** [review]
Remove legacy css from .css that is no longer used such as `header__logo`

**Review by versecafe — APPROVED** [review]
Looks great pulled unused CSS near perfect match to old UI while using tailwind standard units.

**Comment by ADKaster** [comment]
Conflicts, pls rebase

**Comment by TibixDev** [comment]
Should be good now.

**Comment by ADKaster** [comment]
By rebase I did actually mean `git rebase` :) 

merge commits are a sin around here.

**Pull request merged**
